"""First migration

Revision ID: 04d856c698dd
Revises: db73c91a06f2
Create Date: 2023-03-29 18:16:01.539441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d856c698dd'
down_revision = 'db73c91a06f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
