"""First migration

Revision ID: ad6020c6620e
Revises: 85b8b8c5e2f2
Create Date: 2023-03-29 18:09:33.028431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6020c6620e'
down_revision = '85b8b8c5e2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
